{
 "title": "Robot Status",
 "description": "Status information for any individual robot",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "team", "label": "Team", "query": { "query": "label_values(team)" } }
  ]
 },
 "panels": [
  {
   "title": "Power (Board)",
   "type": "stat",
   "description": "General board power.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "best_robot_power_board{team=\"$team\"}"
    }
   ]
  },
  {
   "title": "Power (GPIO)",
   "type": "stat",
   "description": "Power feed for GPIO",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "best_robot_power_gpio{team=\"$team\"}"
    }
   ]
  },
  {
   "title": "Power (Logic)",
   "type": "stat",
   "description": "Power feed for processors and logic.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "best_robot_power_pico{team=\"$team\"}"
    }
   ]
  },
  {
   "title": "Power (Motor Bus A)",
   "type": "stat",
   "description": "Power feed for motor bus A.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "best_robot_power_bus_a{team=\"$team\"}"
    }
   ]
  },
  {
   "title": "Power (Motor Bus B)",
   "type": "stat",
   "description": "Power feed for motor bus B.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "best_robot_power_bus_b{team=\"$team\"}"
    }
   ]
  },
  {
   "title": "Watchdog Disposition",
   "type": "stat",
   "description": "Status of the student processor watchdog.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "best_robot_watchdog_remaining_milliseconds{team=\"$team\"}"
    }
   ]
  },
  {
   "title": "WiFi Signal Strength",
   "type": "timeseries",
   "description": "RSSI packed and ranged to a 1 byte value.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "best_robot_rssi{team=\"$team\"}",
     "legendFormat": "RSSI"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "description": "Battery voltage scaled and packed to a 1 byte number.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "best_robot_battery_voltage{team=\"$team\"}",
     "legendFormat": "RSSI"
    }
   ]
  }
 ]
}